### PR TITLE
Create JSOTemplate compliance workflow

### PR DESCRIPTION
**Pull request by abelsiqueira**
cf. @dpo, @tmigot, @amontoison 

This PR creates a workflow that runs daily and checks that a few files are the same as the ones here:

- `.JuliaFormatter.toml`
- In `.github/workflows/`, `CI.yml`, `CompatHelper.yml`, `Formatter.yml`, `Register.yml`, `TagBot.yml`

It also changed the case of the files to CamelCase, so it is uniform.

This workflow can also be triggered manually.

If there are differences, then a PR is created on that package to fix it.
If there were already PRs from compliance, then the old ones are closed.

This was tested on a single repository (https://github.com/JuliaSmoothOptimizers/DerivativeFreeSolvers.jl/pull/44) and it took a lot of tries and small fixes. So it might lead to a PR hell, which is why I created a PR for review before merging and triggering it.

Along with #18, #19, and #20, it should revamp the workflows of all JSO packages.

### CODE REVIEW

**Comment by amontoison** [comment]
@abelsiqueira 
We should add `.cirrus.yml`, what do you think?
I updated it in Krylov.jl and we can test Apple M1 with CirrusCI now.

**Comment by abelsiqueira** [comment]
> @abelsiqueira We should add `.cirrus.yml`, what do you think? I updated it in Krylov.jl and we can test Apple M1 with CirrusCI now.

I'm fine with that. I don't remember if we have limits in CIRRUS. Is the Apple M1 testing included? Can you create a PR updating the cirrus here, please?

**Comment by amontoison** [comment]
> > @abelsiqueira We should add `.cirrus.yml`, what do you think? I updated it in Krylov.jl and we can test Apple M1 with CirrusCI now.
> 
> I'm fine with that. I don't remember if we have limits in CIRRUS. Is the Apple M1 testing included? Can you create a PR updating the cirrus here, please?

Yes, the Apple M1 testing is included and we don't have limits in CirrusCI.

**Comment by abelsiqueira** [comment]
I've rebased and added Aqua, Invalidations, and cirrus

**Comment by abelsiqueira** [comment]
@dpo, @tmigot, @amontoison, I am ready to merge this.
I have limited the effect to touch only LinearOperators, Krylov, NLPModels, and ADNLPModels.
As an example of what will happen when this is merged, here is a PR made to my fork: https://github.com/abelsiqueira/ADNLPModels.jl/pull/5/files

There are limitations, but this provides a basic structure to change, e.g., CI.yml across many repos.

**Comment by abelsiqueira** [comment]
PS. @amontoison, do you know what are the ARMv8 failures?

**Review by dpo — COMMENTED** [review]
Looks good to me, but where is `check_and_fix_compliance` implemented?

**Comment by amontoison** [comment]
> PS. @amontoison, do you know what are the ARMv8 failures?

It seems that Julia 1.9 was not built for this platform.
We should probably remove it.

Great job Abel!

**Comment by abelsiqueira** [comment]
Thank you for the reviews. `check_and_fix_compliance` is implemented in https://github.com/abelsiqueira/Emporium.jl.
Thanks for checking @amontoison, I will remove that.

**Review by amontoison — APPROVED** [review]

**Review by tmigot — APPROVED** [review]
I like the idea, thanks @abelsiqueira !

**Pull request merged**
